### ISSUE TITLE
Requesting changes

### ISSUE THREAD

**Issue by mistermantas** [hakeemta/millionaire#1]
Hi there!

While this project isn’t the most active, it is the most functional (and visually appealing).

Could you change the game in such a way that:

- It would be possible to choose which set of questions to use beforehand? [Like here](https://github.com/aaronnech/Who-Wants-to-Be-a-Millionaire)
- You have to click to start the clock. Like, if you open the page, the clock shouldn’t immediately start. You should click to see the question, then get it to start.
- Lastly – I haven’t played far enough – but I think the timer should be 15s, 30s, and 45s. If not for the first questions then maybe for the last few?

If you could do this, I’d be very grateful. I want to set this game up for my classroom as a nice “leaving school” present kind of thing. If you aren’t interested, go ahead and close this issue.

**Comment by hakeemta** [comment]
Hi there,

Thanks for the compliment. I will find time to make the provisions.

Cheers!

**Comment by hakeemta** [comment]
I will check this https://github.com/aaronnech/Who-Wants-to-Be-a-Millionaire soon.

**Comment by mistermantas** [comment]
This project finished with great success. Thanks!
